### ISSUE TITLE
selectbox height

### ISSUE THREAD

**Issue by webermax** [gfranko/jquery.selectBoxIt.js#62]
I always need to add the following CSS for a proper height of the selectboxes:

``` css
.selectboxit-container {
    vertical-align:bottom;
}
```
